### ISSUE TITLE
COMP3231 title incorrect

### ISSUE THREAD

**Issue by Walter-Tong** [ivan8882004/HKUCoursePlanner-Reviewer#1]
COMP3231 have a incorrect title of Principles of operating system, it should be Computer Architecture

**Comment by Walter-Tong** [comment]
Ken can u help change the course name of 3231 to the correct one in the config.json

**Comment by kennethkn** [comment]
Fixed in my branch. Can't merge now since I have made other changes in the config that requires corresponding changes in js.
